// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using SWAPI.Data;

namespace SWAPI.Migrations
{
    [DbContext(typeof(SwapiContext))]
    internal class SwapiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("SWAPI.Data.Film", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<decimal>("Average")
                    .HasColumnType("decimal(18,2)");

                b.Property<int>("EpisodeId")
                    .HasColumnType("int");

                b.Property<decimal>("Rate")
                    .HasColumnType("decimal(18,2)");

                b.HasKey("Id");

                b.ToTable("Films");
            });
#pragma warning restore 612, 618
        }
    }
}